const STATES = {
  WELCOME: "WELCOME",
  CATEGORY: "CATEGORY",
  SERVICE: "SERVICE",
  LEAD_NAME: "LEAD_NAME",
  LEAD_PHONE: "LEAD_PHONE",
  LEAD_EMAIL: "LEAD_EMAIL",
  FAQ_SERVICE: "FAQ_SERVICE",
  FAQ_QUESTION: "FAQ_QUESTION",
  FAQ_CUSTOM: "FAQ_CUSTOM",
  FAQ_NEXT: "FAQ_NEXT",
  DONE: "DONE",
};

module.exports = { STATES };
